FROM python:3.14-slim

WORKDIR /usr/local/AI_Node

COPY requirements.txt /usr/local/AI_Node/
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py /usr/local/AI_Node/

CMD ["python3", "main.py"]